# Forward Curve Evaluation

This notebook evaluates forward curve recipes (PCHIP and Kalman) using:
- **Put-call parity**: Compare fitted forwards to options-implied forwards
- **Pillar fit quality**: WMAE between fitted curve and pillar observations
- **Leave-one-expiry-out (LOEO)**: Cross-validation by excluding each pillar

We test on two scenarios:
- **(a)** Full month with binning: 2025-09-01 to 2025-10-01 with 5m bins
- **(b)** Single day with option timestamps: 2025-09-02 using OPTIONS data timestamps

## Key Design

All evaluations use `assign_forwards()` from `okx.recipes.forwards` to match forward
prices to data. This keeps the pipeline consistent and leverages the caching system.

## Imports

In [2]:
%load_ext autoreload
%autoreload 2

from datetime import date, datetime, timedelta
from functools import partial
from typing import Dict, Optional

import numpy as np
import polars as pl
from tqdm import tqdm

from okx.store import OrderbookStore
from okx.recipes.forwards import build_forwards_pchip, build_forwards_kalman, assign_forwards
from okx.recipes.options import prepare_options
from evaluation.forwards_eval import evaluate_parity, summarize_parity, evaluate_pillar_fit, evaluate_loeo, summarize_pillar_fit

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## Store Configuration

In [11]:
store = OrderbookStore(
    data_root="data/okx",
    manifest_path="data/okx/manifest.sqlite"
)

In [16]:
store.clear_cache()

Cleared all caches

## Evaluation Parameters

In [13]:
# Shared parameters
inst_family = 'BTC-USD'

# Scenario (a): Full month with binning
dates_month = [date(2025, 9, 1) + timedelta(days=i) for i in range(30)]  # Sep 1-30
binning_month = '5m'

# Scenario (b): Single day with option timestamps
dates_day = [date(2025, 9, 2)]
binning_day = None  # Will use unique_times from OPTIONS

# Put-call parity filters
moneyness_spread = 0.05

# Recipe configurations
recipes = {
    'pchip': build_forwards_pchip,
    'kalman': build_forwards_kalman
}

batch_days = 5

In [9]:
lf_options = store.get(
    inst_family=inst_family,
    inst_type='OPTION',
    dates=[date(2025, 9, 2), date(2025, 9, 3)],
    depth=0,
    binning='1m',
    features=['trim', 'strip', 'bin'],
    verbose=True,
    benchmark=True
)

[store] Getting BTC-USD/OPTION for 2 dates (depth=0, binning=1m, 3 features)
  - applied 'trim'
  [benchmark] trim: 0.112s
  - applied 'strip'
  [benchmark] strip: 0.000s
  - applied 'bin'
  [benchmark] bin: 2.986s
  [benchmark] Direct build: 3.103s

In [17]:
lf_pillar_fit = evaluate_pillar_fit(
    store=store,
    dates=dates_day,
    inst_family=inst_family,
    forwards_recipe=recipes['kalman'],
    binning=binning_day,
    unique_times=unique_times,
    verbose=True,
)

Preparing pillars for 1 dates...
Constructing pillars for BTC-USD with swap and futures using provided timestamps
 - Time taken to fetch swap and futures: 0:00:04.591243
 - Time taken to align snapshots: 0:00:00.087602

/Users/pascalandreas/Documents/repositories/final-year-project/okx/recipes/pillars.py:56: UserWarning: Sortedness of columns cannot be checked when 'by' groups provided

 - Time taken to concatenate and filter: 0:00:01.463475
 - Time taken to index and sort pillars: 0:00:00.000151
 - Total time taken to prepare pillars: 0:00:06.142471
Assigning kalman forwards to 1 dates using kalman forwards

<sys>:0: UserWarning: Sortedness of columns cannot be checked when 'by' groups provided

 - Time taken to collect data: 0:00:05.814469
[store] Getting derived data via recipe 'build_forwards_kalman' for 1 dates
Building Kalman-filtered Nelson-Siegel forwards for BTC-USD with provided timestamps
Constructing pillars for BTC-USD with swap and futures using provided timestamps
 - Time taken to fetch swap and futures: 0:00:04.371510
 - Time taken to align snapshots: 0:00:00.092540
 - Time taken to concatenate and filter: 0:00:01.451711
 - Time taken to index and sort pillars: 0:00:00.000235
 - Total time taken to prepare pillars: 0:00:05.915996
 - Time taken to prepare and collect pillars: 0:00:11.936863
 - Time taken to build 6312282 snapshots: 0:00:46.097786

Kalman filter:   0%|          | 0/6312282 [00:00<?, ?it/s]

 - Time taken to run Kalman filter: 0:05:02.583037
 - Time taken to convert states to Polars: 0:00:01.456057
 - Total time taken to build Kalman forwards: 0:06:02.073743
 - Time taken to fetch forwards: 0:06:08.938058
 - Time taken to build forward lookup: 0:00:28.979906

Matching forwards:   1%|          | 50000/6312282 [00:16<35:02, 2978.94it/s]IOStream.flush timed out
Matching forwards:   2%|▏         | 100000/6312282 [00:46<43:40, 2370.41it/s]IOStream.flush timed out
Matching forwards:   2%|▏         | 100000/6312282 [01:18<43:40, 2370.41it/s]IOStream.flush timed out
Matching forwards: 100%|██████████| 6312282/6312282 [01:52<00:00, 56339.53it/s]

 - Time taken to match forwards: 0:01:52.474086, matched 44,185,935 / 44,185,935 rows
 - Total time taken to assign forwards: 0:08:30.392050

In [18]:
df_summary = summarize_pillar_fit(lf_pillar_fit).collect()
df_summary.head()
print(df_summary)

shape: (1, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ error_mid_bps_ ┆ error_mid_bps_ ┆ error_bid_bps_ ┆ error_ask_bps ┆ spread_obs_bp ┆ spread_pred_b │
│ mean           ┆ std            ┆ mean           ┆ _mean         ┆ s_mean        ┆ ps_mean       │
│ ---            ┆ ---            ┆ ---            ┆ ---           ┆ ---           ┆ ---           │
│ f64            ┆ f64            ┆ f64            ┆ f64           ┆ f64           ┆ f64           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ 2.190634       ┆ 1.625446       ┆ 2.359713       ┆ 2.102776      ┆ 0.672143      ┆ 0.009795      │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

In [14]:
metrics = lf_errors.group_by(['pillar_idx']).agg([
    pl.col('error_bid_bps').mean().alias('mae_bid_bps'),
    pl.col('error_ask_bps').mean().alias('mae_ask_bps'),
    pl.col('error_mid_bps').mean().alias('mae_mid_bps'),
    ((pl.col('F_ask_obs') < pl.col('F_bid_pred')).sum() / pl.len()).alias('spread_above_pct'),
    ((pl.col('F_bid_obs') > pl.col('F_ask_pred')).sum() / pl.len()).alias('spread_below_pct'),
]).collect()
metrics.sort('pillar_idx').head()

shape: (5, 6)
┌────────────┬─────────────┬─────────────┬─────────────┬──────────────────┬──────────────────┐
│ pillar_idx ┆ mae_bid_bps ┆ mae_ask_bps ┆ mae_mid_bps ┆ spread_above_pct ┆ spread_below_pct │
│ ---        ┆ ---         ┆ ---         ┆ ---         ┆ ---              ┆ ---              │
│ i64        ┆ f64         ┆ f64         ┆ f64         ┆ f64              ┆ f64              │
╞════════════╪═════════════╪═════════════╪═════════════╪══════════════════╪══════════════════╡
│ 1          ┆ 2.011165    ┆ 2.113883    ┆ 2.058759    ┆ 0.129876         ┆ 0.851835         │
│ 2          ┆ 2.285127    ┆ 2.209824    ┆ 2.241302    ┆ 0.564301         ┆ 0.408612         │
│ 3          ┆ 4.017288    ┆ 3.907714    ┆ 3.957395    ┆ 0.753444         ┆ 0.231856         │
│ 4          ┆ 2.673521    ┆ 2.45376     ┆ 2.55275     ┆ 0.685612         ┆ 0.277926         │
│ 5          ┆ 1.823463    ┆ 1.819796    ┆ 1.821302    ┆ 0.663503         ┆ 0.329784         │
└────────────┴─────────────┴─────────────┴─────────────┴──────────────────┴──────────────────┘

In [17]:
lf_loeo = evaluate_loeo(
    store=store,
    dates=dates_month,  # First 3 days only
    inst_family=inst_family,
    forwards_recipe=recipes['kalman'],
    binning=binning_month,
    verbose=True,
)

Running LOEO evaluation for 30 dates...
Constructing pillars for BTC-USD with swap and futures using 5m binning
 - Time taken to fetch swap and futures: 0:00:00.012235
 - Time taken to align snapshots: 0:00:00.000038
 - Time taken to concatenate and filter: 0:00:00.005065
 - Time taken to index and sort pillars: 0:00:00.000072
 - Total time taken to prepare pillars: 0:00:00.017410
Evaluating 7 pillars...

LOEO pillar indices:   0%|          | 0/7 [00:00<?, ?it/s]

Assigning kalman forwards to 30 dates using kalman forwards
 - Time taken to collect data: 0:00:00.000099
[store] Getting derived data via recipe 'build_forwards_kalman' for 30 dates
 - Time taken to fetch forwards: 0:00:00.007432
 - Time taken to build forward lookup: 0:00:00.031602

Matching forwards: 100%|██████████| 8639/8639 [00:00<00:00, 74499.90it/s]
LOEO pillar indices:  14%|█▍        | 1/7 [00:00<00:00,  6.37it/s]

 - Time taken to match forwards: 0:00:00.117449, matched 8,639 / 8,639 rows
 - Total time taken to assign forwards: 0:00:00.156483
Assigning kalman forwards to 30 dates using kalman forwards
 - Time taken to collect data: 0:00:00.000097
[store] Getting derived data via recipe 'build_forwards_kalman' for 30 dates
 - Time taken to fetch forwards: 0:00:00.007546
 - Time taken to build forward lookup: 0:00:00.030093

Matching forwards: 100%|██████████| 8639/8639 [00:00<00:00, 73209.33it/s]
LOEO pillar indices:  29%|██▊       | 2/7 [00:00<00:00,  6.33it/s]

 - Time taken to match forwards: 0:00:00.119913, matched 8,639 / 8,639 rows
 - Total time taken to assign forwards: 0:00:00.157552
Assigning kalman forwards to 30 dates using kalman forwards
 - Time taken to collect data: 0:00:00.000061
[store] Getting derived data via recipe 'build_forwards_kalman' for 30 dates
 - Time taken to fetch forwards: 0:00:00.007806
 - Time taken to build forward lookup: 0:00:00.029600

Matching forwards: 100%|██████████| 8639/8639 [00:00<00:00, 74105.43it/s]
LOEO pillar indices:  43%|████▎     | 3/7 [00:00<00:00,  6.36it/s]

 - Time taken to match forwards: 0:00:00.118130, matched 8,639 / 8,639 rows
 - Total time taken to assign forwards: 0:00:00.155536
Assigning kalman forwards to 30 dates using kalman forwards
 - Time taken to collect data: 0:00:00.000075
[store] Getting derived data via recipe 'build_forwards_kalman' for 30 dates
 - Time taken to fetch forwards: 0:00:00.007903
 - Time taken to build forward lookup: 0:00:00.029578

Matching forwards: 100%|██████████| 8639/8639 [00:00<00:00, 73535.75it/s]
LOEO pillar indices:  57%|█████▋    | 4/7 [00:00<00:00,  6.36it/s]

 - Time taken to match forwards: 0:00:00.118877, matched 8,639 / 8,639 rows
 - Total time taken to assign forwards: 0:00:00.156358
Assigning kalman forwards to 30 dates using kalman forwards
 - Time taken to collect data: 0:00:00.000072
[store] Getting derived data via recipe 'build_forwards_kalman' for 30 dates
 - Time taken to fetch forwards: 0:00:00.007473
 - Time taken to build forward lookup: 0:00:00.029196

Matching forwards: 100%|██████████| 8639/8639 [00:00<00:00, 72405.61it/s]
LOEO pillar indices:  71%|███████▏  | 5/7 [00:00<00:00,  6.34it/s]

 - Time taken to match forwards: 0:00:00.120784, matched 8,639 / 8,639 rows
 - Total time taken to assign forwards: 0:00:00.157453
Assigning kalman forwards to 30 dates using kalman forwards
 - Time taken to collect data: 0:00:00.000092
[store] Getting derived data via recipe 'build_forwards_kalman' for 30 dates
 - Time taken to fetch forwards: 0:00:00.007114
 - Time taken to build forward lookup: 0:00:00.029315

Matching forwards: 100%|██████████| 8639/8639 [00:00<00:00, 47253.31it/s]
LOEO pillar indices:  86%|████████▌ | 6/7 [00:01<00:00,  5.57it/s]

 - Time taken to match forwards: 0:00:00.184349, matched 8,639 / 8,639 rows
 - Total time taken to assign forwards: 0:00:00.220778
Assigning kalman forwards to 30 dates using kalman forwards
 - Time taken to collect data: 0:00:00.000088
[store] Getting derived data via recipe 'build_forwards_kalman' for 30 dates
 - Time taken to fetch forwards: 0:00:00.007527
 - Time taken to build forward lookup: 0:00:00.030362

Matching forwards: 100%|██████████| 7775/7775 [00:00<00:00, 74183.37it/s]
LOEO pillar indices: 100%|██████████| 7/7 [00:01<00:00,  6.06it/s]

 - Time taken to match forwards: 0:00:00.106314, matched 7,775 / 7,775 rows
 - Total time taken to assign forwards: 0:00:00.144203

In [18]:
df_summary = summarize_pillar_fit(lf_loeo).collect()
df_summary.head()

shape: (1, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ error_mid_bps_ ┆ error_mid_bps_ ┆ error_bid_bps_ ┆ error_ask_bps ┆ spread_obs_bp ┆ spread_pred_b │
│ mean           ┆ std            ┆ mean           ┆ _mean         ┆ s_mean        ┆ ps_mean       │
│ ---            ┆ ---            ┆ ---            ┆ ---           ┆ ---           ┆ ---           │
│ f64            ┆ f64            ┆ f64            ┆ f64           ┆ f64           ┆ f64           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ 5.84753        ┆ 7.672553       ┆ 5.900529       ┆ 5.803467      ┆ 0.269112      ┆ 0.008941      │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

In [21]:
metrics = lf_loeo.group_by(['pillar_idx']).agg([
    pl.col('error_bid_bps').mean().alias('mae_bid_bps'),
    pl.col('error_ask_bps').mean().alias('mae_ask_bps'),
    pl.col('error_mid_bps').mean().alias('mae_mid_bps'),
    ((pl.col('F_ask_obs') < pl.col('F_bid_pred')).sum() / pl.len()).alias('spread_above_pct'),
    ((pl.col('F_bid_obs') > pl.col('F_ask_pred')).sum() / pl.len()).alias('spread_below_pct'),
]).collect()
metrics.sort('pillar_idx').head()

shape: (5, 6)
┌────────────┬─────────────┬─────────────┬─────────────┬──────────────────┬──────────────────┐
│ pillar_idx ┆ mae_bid_bps ┆ mae_ask_bps ┆ mae_mid_bps ┆ spread_above_pct ┆ spread_below_pct │
│ ---        ┆ ---         ┆ ---         ┆ ---         ┆ ---              ┆ ---              │
│ i64        ┆ f64         ┆ f64         ┆ f64         ┆ f64              ┆ f64              │
╞════════════╪═════════════╪═════════════╪═════════════╪══════════════════╪══════════════════╡
│ 1          ┆ 2.014199    ┆ 2.116944    ┆ 2.06182     ┆ 0.12976          ┆ 0.85195          │
│ 2          ┆ 2.341062    ┆ 2.265646    ┆ 2.297269    ┆ 0.564996         ┆ 0.408265         │
│ 3          ┆ 4.459518    ┆ 4.350499    ┆ 4.40049     ┆ 0.754254         ┆ 0.233013         │
│ 4          ┆ 3.52679     ┆ 3.303434    ┆ 3.406731    ┆ 0.69603          ┆ 0.278504         │
│ 5          ┆ 2.897832    ┆ 2.89414     ┆ 2.895753    ┆ 0.665471         ┆ 0.330247         │
└────────────┴─────────────┴─────────────┴─────────────┴──────────────────┴──────────────────┘

## Scenario (a): Full Month with Binning

Evaluate both recipes on 2025-09-01 to 2025-09-30 with 5-minute binning.

In [14]:
results_month = {}

for recipe_name, recipe_fn in recipes.items():
    print(f"\n{'='*60}")
    print(f"Evaluating {recipe_name.upper()} on FULL MONTH with {binning_month} binning")
    print(f"{'='*60}\n")
    
    results_month[recipe_name] = {}
    recipe_fn = partial(recipe_fn, inst_family=inst_family, batch_days=batch_days, verbose=True)
    # Put-call parity
    print(f"\n--- Put-Call Parity ---")
    lf_parity = evaluate_parity(
        store=store,
        dates=dates_month,
        inst_family=inst_family,
        forwards_recipe=recipe_fn,
        binning=binning_month,
        moneyness_spread=moneyness_spread,
        batch_days=batch_days,
        verbose=True,
    )
    results_month[recipe_name]['parity'] = lf_parity
    print("\nSummary:")
    print(summarize_parity(lf_parity).collect())
    
    # Pillar fit
    print(f"\n--- Pillar Fit Quality ---")
    lf_pillar_fit = evaluate_pillar_fit(
        store=store,
        dates=dates_month,
        inst_family=inst_family,
        forwards_recipe=recipe_fn,
        binning=binning_month,
        verbose=True,
    )
    results_month[recipe_name]['pillar_fit'] = lf_pillar_fit
    print("\nSummary:")
    print(summarize_pillar_fit(lf_pillar_fit).collect())
    
    # LOEO - sample first 3 days only for speed
    print(f"\n--- Leave-One-Expiry-Out ---")
    lf_loeo = evaluate_loeo(
        store=store,
        dates=dates_month,  # First 3 days only
        inst_family=inst_family,
        forwards_recipe=recipe_fn,
        binning=binning_month,
        verbose=True,
    )
    results_month[recipe_name]['loeo'] = lf_loeo
    
    print("\nSummary:")
    print(summarize_pillar_fit(lf_loeo).collect())

============================================================
Evaluating PCHIP on FULL MONTH with 5m binning
============================================================


--- Put-Call Parity ---
Preparing paired options data for BTC-USD for 30 dates using build_forwards_pchip and 5m binning
[store] Getting BTC-USD/OPTION for 30 dates (depth=1, 5m binning, 7 features)

Processing batches:   0%|          | 0/6 [00:00<?, ?it/s]

 - Time taken to fetch options: 0:00:19.271596
[store] Getting BTC-USD/SPOT for 30 dates (depth=0, 5m binning, 5 features)

Processing batches:   0%|          | 0/6 [00:00<?, ?it/s]

 - Time taken to fetch spot: 0:00:00.682124
 - Time taken for numeraire conversion: 0:00:00.000122
Assigning pchip forwards to 30 dates using pchip forwards
 - Time taken to collect data: 0:00:00.092338
[store] Getting derived data via recipe 'build_forwards_pchip' for 30 dates
Building PCHIP forwards for BTC-USD with 5m binning
Constructing pillars for BTC-USD with swap and futures using 5m binning
 - Time taken to fetch swap and futures: 0:00:15.391872
 - Time taken to align snapshots: 0:00:00.000495
 - Time taken to concatenate and filter: 0:00:00.010703
 - Time taken to index and sort pillars: 0:00:00.000184
 - Total time taken to prepare pillars: 0:00:15.403254
 - Time taken to prepare pillars: 0:00:15.415833
 - Time taken to fit curves: 0:00:00.046721
 - Time taken to smooth curves: 0:00:00.055350
 - Time taken to convert to Polars: 0:00:00.013189
 - Total time taken to build PCHIP forwards: 0:00:15.531093
 - Time taken to fetch forwards: 0:00:15.718449
 - Time taken to build forward lookup: 0:00:00.009269

Matching forwards: 100%|██████████| 8634/8634 [00:01<00:00, 8245.15it/s]

 - Time taken to match forwards: 0:00:01.089069, matched 2,018,638 / 2,018,638 rows
 - Total time taken to assign forwards: 0:00:16.816787
 - Time taken for forwards assignment and moneyness calculation: 0:00:16.824389
 - Total time taken for options data preparation: 0:00:36.778231

Summary:
shape: (1, 7)
┌─────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬─────────────┐
│ n_pairs ┆ error_mid_bp ┆ error_mid_bp ┆ error_bid_bp ┆ error_ask_bp ┆ call_spread_ ┆ put_spread_ │
│ ---     ┆ s_mean       ┆ s_std        ┆ s_mean       ┆ s_mean       ┆ bps_mean     ┆ bps_mean    │
│ u32     ┆ ---          ┆ ---          ┆ ---          ┆ ---          ┆ ---          ┆ ---         │
│         ┆ f64          ┆ f64          ┆ f64          ┆ f64          ┆ f64          ┆ f64         │
╞═════════╪══════════════╪══════════════╪══════════════╪══════════════╪══════════════╪═════════════╡
│ 829853  ┆ 2.742719     ┆ 250.908882   ┆ 2.728613     ┆ 2.75681      ┆ 661.156777   ┆ 636.259293  │
└─────────┴──────────────┴──────────────┴──────────────┴──────────────┴──────────────┴─────────────┘

--- Pillar Fit Quality ---
Preparing pillars for 30 dates...
Constructing pillars for BTC-USD with swap and futures using 5m binning
 - Time taken to fetch swap and futures: 0:00:15.136638
 - Time taken to align snapshots: 0:00:00.000433
 - Time taken to concatenate and filter: 0:00:00.007951
 - Time taken to index and sort pillars: 0:00:00.000158
 - Total time taken to prepare pillars: 0:00:15.145180
Assigning pchip forwards to 30 dates using pchip forwards
 - Time taken to collect data: 0:00:00.010558
[store] Getting derived data via recipe 'build_forwards_pchip' for 30 dates
 - Time taken to fetch forwards: 0:00:00.026576
 - Time taken to build forward lookup: 0:00:00.009171

Matching forwards: 100%|██████████| 8639/8639 [00:01<00:00, 8539.30it/s]

 - Time taken to match forwards: 0:00:01.013699, matched 59,609 / 59,609 rows
 - Total time taken to assign forwards: 0:00:01.049446

Summary:
shape: (1, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ error_mid_bps_ ┆ error_mid_bps_ ┆ error_bid_bps_ ┆ error_ask_bps ┆ spread_obs_bp ┆ spread_pred_b │
│ mean           ┆ std            ┆ mean           ┆ _mean         ┆ s_mean        ┆ ps_mean       │
│ ---            ┆ ---            ┆ ---            ┆ ---           ┆ ---           ┆ ---           │
│ f64            ┆ f64            ┆ f64            ┆ f64           ┆ f64           ┆ f64           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ 2.21978        ┆ 2.371237       ┆ 2.223071       ┆ 2.220039      ┆ 0.269112      ┆ 0.269147      │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

--- Leave-One-Expiry-Out ---
Running LOEO evaluation for 30 dates...
Constructing pillars for BTC-USD with swap and futures using 5m binning
 - Time taken to fetch swap and futures: 0:00:00.013014
 - Time taken to align snapshots: 0:00:00.000039
 - Time taken to concatenate and filter: 0:00:00.008082
 - Time taken to index and sort pillars: 0:00:00.000098
 - Total time taken to prepare pillars: 0:00:00.021233
Evaluating 7 pillars...

LOEO pillar indices:   0%|          | 0/7 [00:00<?, ?it/s]

Assigning pchip forwards to 30 dates using pchip forwards
 - Time taken to collect data: 0:00:00.000122
[store] Getting derived data via recipe 'build_forwards_pchip' for 30 dates
Building PCHIP forwards for BTC-USD with 5m binning
Constructing pillars for BTC-USD with swap and futures using 5m binning
 - Time taken to fetch swap and futures: 0:00:00.015267
 - Time taken to align snapshots: 0:00:00.000035
 - Time taken to concatenate and filter: 0:00:00.007223
 - Time taken to index, drop and sort pillars: 0:00:00.000101
 - Total time taken to prepare pillars: 0:00:00.022626
 - Time taken to prepare pillars: 0:00:00.033995
 - Time taken to fit curves: 0:00:00.037987
 - Time taken to smooth curves: 0:00:00.047742
 - Time taken to convert to Polars: 0:00:00.010909
 - Total time taken to build PCHIP forwards: 0:00:00.130633
 - Time taken to fetch forwards: 0:00:00.185951
 - Time taken to build forward lookup: 0:00:00.432605

Matching forwards: 100%|██████████| 8639/8639 [00:00<00:00, 8970.22it/s]
LOEO pillar indices:  14%|█▍        | 1/7 [00:01<00:09,  1.59s/it]

 - Time taken to match forwards: 0:00:00.964619, matched 8,639 / 8,639 rows
 - Total time taken to assign forwards: 0:00:01.583175
Assigning pchip forwards to 30 dates using pchip forwards
 - Time taken to collect data: 0:00:00.000086
[store] Getting derived data via recipe 'build_forwards_pchip' for 30 dates
Building PCHIP forwards for BTC-USD with 5m binning
Constructing pillars for BTC-USD with swap and futures using 5m binning
 - Time taken to fetch swap and futures: 0:00:00.011692
 - Time taken to align snapshots: 0:00:00.000037
 - Time taken to concatenate and filter: 0:00:00.012445
 - Time taken to index, drop and sort pillars: 0:00:00.000122
 - Total time taken to prepare pillars: 0:00:00.024296
 - Time taken to prepare pillars: 0:00:00.045756
 - Time taken to fit curves: 0:00:00.040841
 - Time taken to smooth curves: 0:00:00.049637
 - Time taken to convert to Polars: 0:00:00.011575
 - Total time taken to build PCHIP forwards: 0:00:00.147809
 - Time taken to fetch forwards: 0:00:00.202697
 - Time taken to build forward lookup: 0:00:00.008461

Matching forwards: 100%|██████████| 8639/8639 [00:00<00:00, 9020.90it/s]
LOEO pillar indices:  29%|██▊       | 2/7 [00:02<00:06,  1.35s/it]

 - Time taken to match forwards: 0:00:00.959247, matched 8,639 / 8,639 rows
 - Total time taken to assign forwards: 0:00:01.170405
Assigning pchip forwards to 30 dates using pchip forwards
 - Time taken to collect data: 0:00:00.000381
[store] Getting derived data via recipe 'build_forwards_pchip' for 30 dates
Building PCHIP forwards for BTC-USD with 5m binning
Constructing pillars for BTC-USD with swap and futures using 5m binning
 - Time taken to fetch swap and futures: 0:00:00.012151
 - Time taken to align snapshots: 0:00:00.000043
 - Time taken to concatenate and filter: 0:00:00.008122
 - Time taken to index, drop and sort pillars: 0:00:00.000104
 - Total time taken to prepare pillars: 0:00:00.020420
 - Time taken to prepare pillars: 0:00:00.043649
 - Time taken to fit curves: 0:00:00.038978
 - Time taken to smooth curves: 0:00:00.047917
 - Time taken to convert to Polars: 0:00:00.011115
 - Total time taken to build PCHIP forwards: 0:00:00.141659
 - Time taken to fetch forwards: 0:00:00.207712
 - Time taken to build forward lookup: 0:00:00.008402

Matching forwards: 100%|██████████| 8639/8639 [00:00<00:00, 9045.14it/s]
LOEO pillar indices:  43%|████▎     | 3/7 [00:03<00:05,  1.28s/it]

 - Time taken to match forwards: 0:00:00.956562, matched 8,639 / 8,639 rows
 - Total time taken to assign forwards: 0:00:01.172676
Assigning pchip forwards to 30 dates using pchip forwards
 - Time taken to collect data: 0:00:00.000093
[store] Getting derived data via recipe 'build_forwards_pchip' for 30 dates
Building PCHIP forwards for BTC-USD with 5m binning
Constructing pillars for BTC-USD with swap and futures using 5m binning
 - Time taken to fetch swap and futures: 0:00:00.019038
 - Time taken to align snapshots: 0:00:00.000033
 - Time taken to concatenate and filter: 0:00:00.017604
 - Time taken to index, drop and sort pillars: 0:00:00.000110
 - Total time taken to prepare pillars: 0:00:00.036785
 - Time taken to prepare pillars: 0:00:00.057675
 - Time taken to fit curves: 0:00:00.040068
 - Time taken to smooth curves: 0:00:00.047191
 - Time taken to convert to Polars: 0:00:00.010712
 - Total time taken to build PCHIP forwards: 0:00:00.155646
 - Time taken to fetch forwards: 0:00:00.213565
 - Time taken to build forward lookup: 0:00:00.008770

Matching forwards: 100%|██████████| 8639/8639 [00:00<00:00, 9111.47it/s]
LOEO pillar indices:  57%|█████▋    | 4/7 [00:05<00:03,  1.24s/it]

 - Time taken to match forwards: 0:00:00.949604, matched 8,639 / 8,639 rows
 - Total time taken to assign forwards: 0:00:01.171939
Assigning pchip forwards to 30 dates using pchip forwards
 - Time taken to collect data: 0:00:00.000097
[store] Getting derived data via recipe 'build_forwards_pchip' for 30 dates
Building PCHIP forwards for BTC-USD with 5m binning
Constructing pillars for BTC-USD with swap and futures using 5m binning
 - Time taken to fetch swap and futures: 0:00:00.012287
 - Time taken to align snapshots: 0:00:00.000024
 - Time taken to concatenate and filter: 0:00:00.016793
 - Time taken to index, drop and sort pillars: 0:00:00.000104
 - Total time taken to prepare pillars: 0:00:00.029208
 - Time taken to prepare pillars: 0:00:00.053815
 - Time taken to fit curves: 0:00:00.039063
 - Time taken to smooth curves: 0:00:00.048826
 - Time taken to convert to Polars: 0:00:00.010725
 - Total time taken to build PCHIP forwards: 0:00:00.152429
 - Time taken to fetch forwards: 0:00:00.204764
 - Time taken to build forward lookup: 0:00:00.008038

Matching forwards: 100%|██████████| 8639/8639 [00:00<00:00, 9125.93it/s]
LOEO pillar indices:  71%|███████▏  | 5/7 [00:06<00:02,  1.21s/it]

 - Time taken to match forwards: 0:00:00.948107, matched 8,639 / 8,639 rows
 - Total time taken to assign forwards: 0:00:01.160909
Assigning pchip forwards to 30 dates using pchip forwards
 - Time taken to collect data: 0:00:00.000094
[store] Getting derived data via recipe 'build_forwards_pchip' for 30 dates
Building PCHIP forwards for BTC-USD with 5m binning
Constructing pillars for BTC-USD with swap and futures using 5m binning
 - Time taken to fetch swap and futures: 0:00:00.012686
 - Time taken to align snapshots: 0:00:00.000035
 - Time taken to concatenate and filter: 0:00:00.027531
 - Time taken to index, drop and sort pillars: 0:00:00.000103
 - Total time taken to prepare pillars: 0:00:00.040355
 - Time taken to prepare pillars: 0:00:00.058365
 - Time taken to fit curves: 0:00:00.038630
 - Time taken to smooth curves: 0:00:00.047654
 - Time taken to convert to Polars: 0:00:00.010644
 - Total time taken to build PCHIP forwards: 0:00:00.155293
 - Time taken to fetch forwards: 0:00:00.210871
 - Time taken to build forward lookup: 0:00:00.008270

Matching forwards: 100%|██████████| 8639/8639 [00:00<00:00, 8832.89it/s]
LOEO pillar indices:  86%|████████▌ | 6/7 [00:07<00:01,  1.21s/it]

 - Time taken to match forwards: 0:00:00.979698, matched 8,639 / 8,639 rows
 - Total time taken to assign forwards: 0:00:01.198839
Assigning pchip forwards to 30 dates using pchip forwards
 - Time taken to collect data: 0:00:00.000097
[store] Getting derived data via recipe 'build_forwards_pchip' for 30 dates
Building PCHIP forwards for BTC-USD with 5m binning
Constructing pillars for BTC-USD with swap and futures using 5m binning
 - Time taken to fetch swap and futures: 0:00:00.012639
 - Time taken to align snapshots: 0:00:00.000035
 - Time taken to concatenate and filter: 0:00:00.021760
 - Time taken to index, drop and sort pillars: 0:00:00.000130
 - Total time taken to prepare pillars: 0:00:00.034564
 - Time taken to prepare pillars: 0:00:00.072841
 - Time taken to fit curves: 0:00:00.038604
 - Time taken to smooth curves: 0:00:00.048174
 - Time taken to convert to Polars: 0:00:00.010784
 - Total time taken to build PCHIP forwards: 0:00:00.170403
 - Time taken to fetch forwards: 0:00:00.231426
 - Time taken to build forward lookup: 0:00:00.076637

Matching forwards: 100%|██████████| 7775/7775 [00:00<00:00, 9045.63it/s]
LOEO pillar indices: 100%|██████████| 7/7 [00:08<00:00,  1.24s/it]

 - Time taken to match forwards: 0:00:00.861105, matched 7,775 / 7,775 rows
 - Total time taken to assign forwards: 0:00:01.169168

Summary:
shape: (1, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ error_mid_bps_ ┆ error_mid_bps_ ┆ error_bid_bps_ ┆ error_ask_bps ┆ spread_obs_bp ┆ spread_pred_b │
│ mean           ┆ std            ┆ mean           ┆ _mean         ┆ s_mean        ┆ ps_mean       │
│ ---            ┆ ---            ┆ ---            ┆ ---           ┆ ---           ┆ ---           │
│ f64            ┆ f64            ┆ f64            ┆ f64           ┆ f64           ┆ f64           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ 6.699816       ┆ 10.298761      ┆ 6.517625       ┆ 6.89727       ┆ 0.269112      ┆ 0.514074      │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

============================================================
Evaluating KALMAN on FULL MONTH with 5m binning
============================================================


--- Put-Call Parity ---
Preparing paired options data for BTC-USD for 30 dates using build_forwards_kalman and 5m binning
[store] Getting BTC-USD/OPTION for 30 dates (depth=1, 5m binning, 7 features)

Processing batches:   0%|          | 0/6 [00:00<?, ?it/s]

 - Time taken to fetch options: 0:00:00.009939
[store] Getting BTC-USD/SPOT for 30 dates (depth=0, 5m binning, 5 features)

Processing batches:   0%|          | 0/6 [00:00<?, ?it/s]

 - Time taken to fetch spot: 0:00:00.009960
 - Time taken for numeraire conversion: 0:00:00.000140
Assigning kalman forwards to 30 dates using kalman forwards
 - Time taken to collect data: 0:00:00.150474
[store] Getting derived data via recipe 'build_forwards_kalman' for 30 dates
Building Kalman-filtered Nelson-Siegel forwards for BTC-USD with 5m binning
Constructing pillars for BTC-USD with swap and futures using 5m binning
 - Time taken to fetch swap and futures: 0:00:00.014857
 - Time taken to align snapshots: 0:00:00.000032
 - Time taken to concatenate and filter: 0:00:00.012296
 - Time taken to index and sort pillars: 0:00:00.000125
 - Total time taken to prepare pillars: 0:00:00.027310
 - Time taken to prepare and collect pillars: 0:00:00.053296
 - Time taken to build 8639 snapshots: 0:00:00.045817

Kalman filter:   0%|          | 0/8639 [00:00<?, ?it/s]

 - Time taken to run Kalman filter: 0:00:00.433437
 - Time taken to convert states to Polars: 0:00:00.001511
 - Total time taken to build Kalman forwards: 0:00:00.534061
 - Time taken to fetch forwards: 0:00:00.741827
 - Time taken to build forward lookup: 0:00:00.037279

Matching forwards: 100%|██████████| 8634/8634 [00:00<00:00, 46057.60it/s]

 - Time taken to match forwards: 0:00:00.213680, matched 2,018,638 / 2,018,638 rows
 - Total time taken to assign forwards: 0:00:00.992786
 - Time taken for forwards assignment and moneyness calculation: 0:00:00.998808
 - Total time taken for options data preparation: 0:00:01.018847

Summary:
shape: (1, 7)
┌─────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬─────────────┐
│ n_pairs ┆ error_mid_bp ┆ error_mid_bp ┆ error_bid_bp ┆ error_ask_bp ┆ call_spread_ ┆ put_spread_ │
│ ---     ┆ s_mean       ┆ s_std        ┆ s_mean       ┆ s_mean       ┆ bps_mean     ┆ bps_mean    │
│ u32     ┆ ---          ┆ ---          ┆ ---          ┆ ---          ┆ ---          ┆ ---         │
│         ┆ f64          ┆ f64          ┆ f64          ┆ f64          ┆ f64          ┆ f64         │
╞═════════╪══════════════╪══════════════╪══════════════╪══════════════╪══════════════╪═════════════╡
│ 829922  ┆ 2.942085     ┆ 250.918325   ┆ 2.843552     ┆ 3.040597     ┆ 659.96113    ┆ 636.680592  │
└─────────┴──────────────┴──────────────┴──────────────┴──────────────┴──────────────┴─────────────┘

--- Pillar Fit Quality ---
Preparing pillars for 30 dates...
Constructing pillars for BTC-USD with swap and futures using 5m binning
 - Time taken to fetch swap and futures: 0:00:00.015781
 - Time taken to align snapshots: 0:00:00.000038
 - Time taken to concatenate and filter: 0:00:00.013060
 - Time taken to index and sort pillars: 0:00:00.000097
 - Total time taken to prepare pillars: 0:00:00.028976
Assigning kalman forwards to 30 dates using kalman forwards
 - Time taken to collect data: 0:00:00.022574
[store] Getting derived data via recipe 'build_forwards_kalman' for 30 dates
 - Time taken to fetch forwards: 0:00:00.031834
 - Time taken to build forward lookup: 0:00:00.035050

Matching forwards: 100%|██████████| 8639/8639 [00:00<00:00, 56301.09it/s]

 - Time taken to match forwards: 0:00:00.154874, matched 59,609 / 59,609 rows
 - Total time taken to assign forwards: 0:00:00.221758

Summary:
shape: (1, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ error_mid_bps_ ┆ error_mid_bps_ ┆ error_bid_bps_ ┆ error_ask_bps ┆ spread_obs_bp ┆ spread_pred_b │
│ mean           ┆ std            ┆ mean           ┆ _mean         ┆ s_mean        ┆ ps_mean       │
│ ---            ┆ ---            ┆ ---            ┆ ---           ┆ ---           ┆ ---           │
│ f64            ┆ f64            ┆ f64            ┆ f64           ┆ f64           ┆ f64           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ 2.71083        ┆ 2.144757       ┆ 2.765862       ┆ 2.672026      ┆ 0.269112      ┆ 0.008941      │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

--- Leave-One-Expiry-Out ---
Running LOEO evaluation for 30 dates...
Constructing pillars for BTC-USD with swap and futures using 5m binning
 - Time taken to fetch swap and futures: 0:00:00.014614
 - Time taken to align snapshots: 0:00:00.000031
 - Time taken to concatenate and filter: 0:00:00.010000
 - Time taken to index and sort pillars: 0:00:00.000077
 - Total time taken to prepare pillars: 0:00:00.024722
Evaluating 7 pillars...

LOEO pillar indices:   0%|          | 0/7 [00:00<?, ?it/s]

Assigning kalman forwards to 30 dates using kalman forwards
 - Time taken to collect data: 0:00:00.000136
[store] Getting derived data via recipe 'build_forwards_kalman' for 30 dates
Building Kalman-filtered Nelson-Siegel forwards for BTC-USD with 5m binning
Constructing pillars for BTC-USD with swap and futures using 5m binning
 - Time taken to fetch swap and futures: 0:00:00.016673
 - Time taken to align snapshots: 0:00:00.000027
 - Time taken to concatenate and filter: 0:00:00.003631
 - Time taken to index, drop and sort pillars: 0:00:00.000087
 - Total time taken to prepare pillars: 0:00:00.020418
 - Time taken to prepare and collect pillars: 0:00:00.029226
 - Time taken to build 8639 snapshots: 0:00:00.043929

Kalman filter:   0%|          | 0/8639 [00:00<?, ?it/s]

 - Time taken to run Kalman filter: 0:00:00.400357
 - Time taken to convert states to Polars: 0:00:00.001335
 - Total time taken to build Kalman forwards: 0:00:00.474847
 - Time taken to fetch forwards: 0:00:00.525245
 - Time taken to build forward lookup: 0:00:00.036338

Matching forwards: 100%|██████████| 8639/8639 [00:00<00:00, 57002.92it/s]
LOEO pillar indices:  14%|█▍        | 1/7 [00:00<00:04,  1.39it/s]

 - Time taken to match forwards: 0:00:00.153231, matched 8,639 / 8,639 rows
 - Total time taken to assign forwards: 0:00:00.714814
Assigning kalman forwards to 30 dates using kalman forwards
 - Time taken to collect data: 0:00:00.000087
[store] Getting derived data via recipe 'build_forwards_kalman' for 30 dates
Building Kalman-filtered Nelson-Siegel forwards for BTC-USD with 5m binning
Constructing pillars for BTC-USD with swap and futures using 5m binning
 - Time taken to fetch swap and futures: 0:00:00.015079
 - Time taken to align snapshots: 0:00:00.000031
 - Time taken to concatenate and filter: 0:00:00.011838
 - Time taken to index, drop and sort pillars: 0:00:00.000099
 - Total time taken to prepare pillars: 0:00:00.027047
 - Time taken to prepare and collect pillars: 0:00:00.048829
 - Time taken to build 8639 snapshots: 0:00:00.044688

Kalman filter:   0%|          | 0/8639 [00:00<?, ?it/s]

 - Time taken to run Kalman filter: 0:00:00.399017
 - Time taken to convert states to Polars: 0:00:00.001470
 - Total time taken to build Kalman forwards: 0:00:00.494004
 - Time taken to fetch forwards: 0:00:00.541619
 - Time taken to build forward lookup: 0:00:00.032190

Matching forwards: 100%|██████████| 8639/8639 [00:00<00:00, 67823.42it/s]
LOEO pillar indices:  29%|██▊       | 2/7 [00:01<00:03,  1.40it/s]

 - Time taken to match forwards: 0:00:00.128891, matched 8,639 / 8,639 rows
 - Total time taken to assign forwards: 0:00:00.702700
Assigning kalman forwards to 30 dates using kalman forwards
 - Time taken to collect data: 0:00:00.000096
[store] Getting derived data via recipe 'build_forwards_kalman' for 30 dates
Building Kalman-filtered Nelson-Siegel forwards for BTC-USD with 5m binning
Constructing pillars for BTC-USD with swap and futures using 5m binning
 - Time taken to fetch swap and futures: 0:00:00.014056
 - Time taken to align snapshots: 0:00:00.000034
 - Time taken to concatenate and filter: 0:00:00.010728
 - Time taken to index, drop and sort pillars: 0:00:00.000095
 - Total time taken to prepare pillars: 0:00:00.024913
 - Time taken to prepare and collect pillars: 0:00:00.039590
 - Time taken to build 8639 snapshots: 0:00:00.046944

Kalman filter:   0%|          | 0/8639 [00:00<?, ?it/s]

 - Time taken to run Kalman filter: 0:00:00.399773
 - Time taken to convert states to Polars: 0:00:00.001384
 - Total time taken to build Kalman forwards: 0:00:00.487691
 - Time taken to fetch forwards: 0:00:00.540922
 - Time taken to build forward lookup: 0:00:00.097123

Matching forwards: 100%|██████████| 8639/8639 [00:00<00:00, 67208.13it/s]
LOEO pillar indices:  43%|████▎     | 3/7 [00:02<00:02,  1.35it/s]

 - Time taken to match forwards: 0:00:00.130032, matched 8,639 / 8,639 rows
 - Total time taken to assign forwards: 0:00:00.768077
Assigning kalman forwards to 30 dates using kalman forwards
 - Time taken to collect data: 0:00:00.000089
[store] Getting derived data via recipe 'build_forwards_kalman' for 30 dates
Building Kalman-filtered Nelson-Siegel forwards for BTC-USD with 5m binning
Constructing pillars for BTC-USD with swap and futures using 5m binning
 - Time taken to fetch swap and futures: 0:00:00.013591
 - Time taken to align snapshots: 0:00:00.000032
 - Time taken to concatenate and filter: 0:00:00.008890
 - Time taken to index, drop and sort pillars: 0:00:00.000108
 - Total time taken to prepare pillars: 0:00:00.022621
 - Time taken to prepare and collect pillars: 0:00:00.036956
 - Time taken to build 8639 snapshots: 0:00:00.046709

Kalman filter:   0%|          | 0/8639 [00:00<?, ?it/s]

 - Time taken to run Kalman filter: 0:00:00.402867
 - Time taken to convert states to Polars: 0:00:00.001349
 - Total time taken to build Kalman forwards: 0:00:00.487881
 - Time taken to fetch forwards: 0:00:00.535325
 - Time taken to build forward lookup: 0:00:00.033061

Matching forwards: 100%|██████████| 8639/8639 [00:00<00:00, 65130.19it/s]
LOEO pillar indices:  57%|█████▋    | 4/7 [00:02<00:02,  1.37it/s]

 - Time taken to match forwards: 0:00:00.134247, matched 8,639 / 8,639 rows
 - Total time taken to assign forwards: 0:00:00.702633
Assigning kalman forwards to 30 dates using kalman forwards
 - Time taken to collect data: 0:00:00.000082
[store] Getting derived data via recipe 'build_forwards_kalman' for 30 dates
Building Kalman-filtered Nelson-Siegel forwards for BTC-USD with 5m binning
Constructing pillars for BTC-USD with swap and futures using 5m binning
 - Time taken to fetch swap and futures: 0:00:00.012928
 - Time taken to align snapshots: 0:00:00.000032
 - Time taken to concatenate and filter: 0:00:00.005093
 - Time taken to index, drop and sort pillars: 0:00:00.000102
 - Total time taken to prepare pillars: 0:00:00.018155
 - Time taken to prepare and collect pillars: 0:00:00.032977
 - Time taken to build 8639 snapshots: 0:00:00.046260

Kalman filter:   0%|          | 0/8639 [00:00<?, ?it/s]

 - Time taken to run Kalman filter: 0:00:00.422797
 - Time taken to convert states to Polars: 0:00:00.001401
 - Total time taken to build Kalman forwards: 0:00:00.503435
 - Time taken to fetch forwards: 0:00:00.558798
 - Time taken to build forward lookup: 0:00:00.038103

Matching forwards: 100%|██████████| 8639/8639 [00:00<00:00, 67065.33it/s]
LOEO pillar indices:  71%|███████▏  | 5/7 [00:03<00:01,  1.37it/s]

 - Time taken to match forwards: 0:00:00.130458, matched 8,639 / 8,639 rows
 - Total time taken to assign forwards: 0:00:00.727359
Assigning kalman forwards to 30 dates using kalman forwards
 - Time taken to collect data: 0:00:00.000070
[store] Getting derived data via recipe 'build_forwards_kalman' for 30 dates
Building Kalman-filtered Nelson-Siegel forwards for BTC-USD with 5m binning
Constructing pillars for BTC-USD with swap and futures using 5m binning
 - Time taken to fetch swap and futures: 0:00:00.013656
 - Time taken to align snapshots: 0:00:00.000035
 - Time taken to concatenate and filter: 0:00:00.005151
 - Time taken to index, drop and sort pillars: 0:00:00.000081
 - Total time taken to prepare pillars: 0:00:00.018923
 - Time taken to prepare and collect pillars: 0:00:00.028775
 - Time taken to build 8639 snapshots: 0:00:00.046604

Kalman filter:   0%|          | 0/8639 [00:00<?, ?it/s]

 - Time taken to run Kalman filter: 0:00:00.404890
 - Time taken to convert states to Polars: 0:00:00.001326
 - Total time taken to build Kalman forwards: 0:00:00.481595
 - Time taken to fetch forwards: 0:00:00.527043
 - Time taken to build forward lookup: 0:00:00.032100

Matching forwards: 100%|██████████| 8639/8639 [00:00<00:00, 68297.31it/s]
LOEO pillar indices:  86%|████████▌ | 6/7 [00:04<00:00,  1.40it/s]

 - Time taken to match forwards: 0:00:00.128217, matched 8,639 / 8,639 rows
 - Total time taken to assign forwards: 0:00:00.687360
Assigning kalman forwards to 30 dates using kalman forwards
 - Time taken to collect data: 0:00:00.000073
[store] Getting derived data via recipe 'build_forwards_kalman' for 30 dates
Building Kalman-filtered Nelson-Siegel forwards for BTC-USD with 5m binning
Constructing pillars for BTC-USD with swap and futures using 5m binning
 - Time taken to fetch swap and futures: 0:00:00.012923
 - Time taken to align snapshots: 0:00:00.000035
 - Time taken to concatenate and filter: 0:00:00.007259
 - Time taken to index, drop and sort pillars: 0:00:00.000113
 - Total time taken to prepare pillars: 0:00:00.020330
 - Time taken to prepare and collect pillars: 0:00:00.031501
 - Time taken to build 8639 snapshots: 0:00:00.047729

Kalman filter:   0%|          | 0/8639 [00:00<?, ?it/s]

 - Time taken to run Kalman filter: 0:00:00.427296
 - Time taken to convert states to Polars: 0:00:00.001414
 - Total time taken to build Kalman forwards: 0:00:00.507940
 - Time taken to fetch forwards: 0:00:00.552112
 - Time taken to build forward lookup: 0:00:00.037354

Matching forwards: 100%|██████████| 7775/7775 [00:00<00:00, 65458.78it/s]
LOEO pillar indices: 100%|██████████| 7/7 [00:05<00:00,  1.39it/s]

 - Time taken to match forwards: 0:00:00.120619, matched 7,775 / 7,775 rows
 - Total time taken to assign forwards: 0:00:00.710085

Summary:
shape: (1, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ error_mid_bps_ ┆ error_mid_bps_ ┆ error_bid_bps_ ┆ error_ask_bps ┆ spread_obs_bp ┆ spread_pred_b │
│ mean           ┆ std            ┆ mean           ┆ _mean         ┆ s_mean        ┆ ps_mean       │
│ ---            ┆ ---            ┆ ---            ┆ ---           ┆ ---           ┆ ---           │
│ f64            ┆ f64            ┆ f64            ┆ f64           ┆ f64           ┆ f64           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ 5.84753        ┆ 7.672553       ┆ 5.900529       ┆ 5.803467      ┆ 0.269112      ┆ 0.008941      │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

## Scenario (b): Single Day with Option Timestamps

Evaluate both recipes on 2025-09-02 using unique timestamps from OPTIONS orderbook.

In [9]:
# Get unique timestamps from OPTIONS orderbook
print("Fetching unique timestamps from OPTIONS orderbook...")
unique_times = store.get(
    inst_family=inst_family,
    inst_type='OPTION',
    dates=dates_day,
    depth=0,
    features=['trim', 'strip'],
    verbose=True
).select('timeMs').unique().sort('timeMs').collect().to_series().to_list()

print(f"Found {len(unique_times)} unique timestamps")

Fetching unique timestamps from OPTIONS orderbook...
[store] Getting BTC-USD/OPTION for 1 dates (depth=0, provided timestamps, 2 features)
Found 6312288 unique timestamps

In [15]:
results_day = {}

for recipe_name, recipe_fn in recipes.items():
    print(f"\n{'='*60}")
    print(f"Evaluating {recipe_name.upper()} on SINGLE DAY with OPTION TIMESTAMPS")
    print(f"{'='*60}\n")
    
    results_day[recipe_name] = {}
    recipe_fn = partial(recipe_fn, inst_family=inst_family, batch_days=batch_days, verbose=True)

    # Put-call parity
    print(f"\n--- Put-Call Parity ---")
    lf_parity = evaluate_parity(
        store=store,
        dates=dates_day,
        inst_family=inst_family,
        forwards_recipe=recipe_fn,
        binning=binning_day,
        verbose=True,
    )
    results_day[recipe_name]['parity'] = lf_parity
    print("\nSummary:")
    print(summarize_parity(lf_parity).collect())
    
    # Pillar fit
    print(f"\n--- Pillar Fit Quality ---")
    lf_pillar_fit = evaluate_pillar_fit(
        store=store,
        dates=dates_day,
        inst_family=inst_family,
        forwards_recipe=recipe_fn,
        binning=binning_day,
        unique_times=unique_times,
        verbose=True,
    )
    results_day[recipe_name]['pillar_fit'] = lf_pillar_fit
    print("\nSummary:")
    print(summarize_pillar_fit(lf_pillar_fit).collect())
    
    # LOEO - sample every 50th timestamp for speed
    print(f"\n--- Leave-One-Expiry-Out (sampled timestamps) ---")
    unique_times_sampled = unique_times[::50]  # Sample every 50th
    print(f"Using {len(unique_times_sampled)} sampled timestamps")
    
    lf_loeo = evaluate_loeo(
        store=store,
        dates=dates_day,
        inst_family=inst_family,
        forwards_recipe=recipe_fn,
        binning=binning_day,
        unique_times=unique_times_sampled,
        verbose=True,
    )
    results_day[recipe_name]['loeo'] = lf_loeo
    print("\nSummary:")
    print(summarize_pillar_fit(lf_loeo).collect())

============================================================
Evaluating PCHIP on SINGLE DAY with OPTION TIMESTAMPS
============================================================


--- Put-Call Parity ---
Preparing paired options data for BTC-USD for 1 dates using build_forwards_pchip
[store] Getting BTC-USD/OPTION for 1 dates (depth=1, provided timestamps, 6 features)
 - Time taken to fetch options: 0:00:07.980524
[store] Getting BTC-USD/SPOT for 1 dates (depth=0, provided timestamps, 4 features)
 - Time taken to fetch spot: 0:00:00.258086
 - Time taken for numeraire conversion: 0:00:00.000137
Assigning pchip forwards to 1 dates using pchip forwards
 - Time taken to collect data: 0:00:00.530774
[store] Getting derived data via recipe 'build_forwards_pchip' for 1 dates
Building PCHIP forwards for BTC-USD with provided timestamps
Constructing pillars for BTC-USD with swap and futures using provided timestamps
 - Time taken to fetch swap and futures: 0:00:04.479840
 - Time taken to align snapshots: 0:00:00.006592

/Users/pascalandreas/Documents/repositories/final-year-project/okx/recipes/pillars.py:56: UserWarning: Sortedness of columns cannot be checked when 'by' groups provided

 - Time taken to concatenate and filter: 0:00:00.711674
 - Time taken to index and sort pillars: 0:00:00.000155
 - Total time taken to prepare pillars: 0:00:05.198261
 - Time taken to prepare pillars: 0:00:06.196085
 - Time taken to fit curves: 0:00:02.084658
 - Time taken to smooth curves: 0:00:02.657504
 - Time taken to convert to Polars: 0:00:00.556632
 - Total time taken to build PCHIP forwards: 0:00:11.494879
 - Time taken to fetch forwards: 0:00:12.536056
 - Time taken to build forward lookup: 0:00:00.688732

Matching forwards: 100%|██████████| 399680/399680 [00:44<00:00, 8983.99it/s]

 - Time taken to match forwards: 0:00:44.496841, matched 749,637 / 749,637 rows
 - Total time taken to assign forwards: 0:00:57.721629
 - Time taken for forwards assignment and moneyness calculation: 0:00:57.814392
 - Total time taken for options data preparation: 0:01:06.053139

Summary:
shape: (1, 7)
┌─────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬─────────────┐
│ n_pairs ┆ error_mid_bp ┆ error_mid_bp ┆ error_bid_bp ┆ error_ask_bp ┆ call_spread_ ┆ put_spread_ │
│ ---     ┆ s_mean       ┆ s_std        ┆ s_mean       ┆ s_mean       ┆ bps_mean     ┆ bps_mean    │
│ u32     ┆ ---          ┆ ---          ┆ ---          ┆ ---          ┆ ---          ┆ ---         │
│         ┆ f64          ┆ f64          ┆ f64          ┆ f64          ┆ f64          ┆ f64         │
╞═════════╪══════════════╪══════════════╪══════════════╪══════════════╪══════════════╪═════════════╡
│ 682999  ┆ 8.586849     ┆ 180.928034   ┆ 8.824834     ┆ 8.348858     ┆ 462.204175   ┆ 475.265601  │
└─────────┴──────────────┴──────────────┴──────────────┴──────────────┴──────────────┴─────────────┘

--- Pillar Fit Quality ---
Preparing pillars for 1 dates...
Constructing pillars for BTC-USD with swap and futures using provided timestamps
 - Time taken to fetch swap and futures: 0:00:04.383010
 - Time taken to align snapshots: 0:00:00.096064
 - Time taken to concatenate and filter: 0:00:01.285453
 - Time taken to index and sort pillars: 0:00:00.000217
 - Total time taken to prepare pillars: 0:00:05.764744
Assigning pchip forwards to 1 dates using pchip forwards
 - Time taken to collect data: 0:00:04.992317
[store] Getting derived data via recipe 'build_forwards_pchip' for 1 dates
 - Time taken to fetch forwards: 0:00:05.085926
 - Time taken to build forward lookup: 0:00:00.714472

Matching forwards: 100%|██████████| 6312282/6312282 [00:46<00:00, 134364.12it/s]

 - Time taken to match forwards: 0:00:47.115656, matched 2,797,748 / 44,185,935 rows
 - Total time taken to assign forwards: 0:00:52.916054
Skipped 5,912,602 timestamp groups with no forward curve

Summary:
shape: (1, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ error_mid_bps_ ┆ error_mid_bps_ ┆ error_bid_bps_ ┆ error_ask_bps ┆ spread_obs_bp ┆ spread_pred_b │
│ mean           ┆ std            ┆ mean           ┆ _mean         ┆ s_mean        ┆ ps_mean       │
│ ---            ┆ ---            ┆ ---            ┆ ---           ┆ ---           ┆ ---           │
│ f64            ┆ f64            ┆ f64            ┆ f64           ┆ f64           ┆ f64           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ NaN            ┆ NaN            ┆ NaN            ┆ NaN           ┆ 0.672143      ┆ NaN           │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

--- Leave-One-Expiry-Out (sampled timestamps) ---
Using 126246 sampled timestamps
Running LOEO evaluation for 1 dates...
Constructing pillars for BTC-USD with swap and futures using provided timestamps
 - Time taken to fetch swap and futures: 0:00:00.000824
 - Time taken to align snapshots: 0:00:00.008333
 - Time taken to concatenate and filter: 0:00:00.609702
 - Time taken to index and sort pillars: 0:00:00.000172
 - Total time taken to prepare pillars: 0:00:00.619031
Evaluating 7 pillars...

LOEO pillar indices:   0%|          | 0/7 [00:00<?, ?it/s]

Assigning pchip forwards to 1 dates using pchip forwards
 - Time taken to collect data: 0:00:00.000130
[store] Getting derived data via recipe 'build_forwards_pchip' for 1 dates
Building PCHIP forwards for BTC-USD with provided timestamps
Constructing pillars for BTC-USD with swap and futures using provided timestamps
 - Time taken to fetch swap and futures: 0:00:00.000576
 - Time taken to align snapshots: 0:00:00.001965
 - Time taken to concatenate and filter: 0:00:00.628976
 - Time taken to index, drop and sort pillars: 0:00:00.000219
 - Total time taken to prepare pillars: 0:00:00.631736
 - Time taken to prepare pillars: 0:00:01.396139
 - Time taken to fit curves: 0:00:00.614603
 - Time taken to smooth curves: 0:00:00.803765
 - Time taken to convert to Polars: 0:00:00.167016
 - Total time taken to build PCHIP forwards: 0:00:02.981523
 - Time taken to fetch forwards: 0:00:03.122583
 - Time taken to build forward lookup: 0:00:00.202407

Matching forwards: 100%|██████████| 126245/126245 [00:13<00:00, 9087.24it/s]
LOEO pillar indices:  14%|█▍        | 1/7 [00:17<01:43, 17.24s/it]

 - Time taken to match forwards: 0:00:13.894997, matched 126,245 / 126,245 rows
 - Total time taken to assign forwards: 0:00:17.219987
Assigning pchip forwards to 1 dates using pchip forwards
 - Time taken to collect data: 0:00:00.000094
[store] Getting derived data via recipe 'build_forwards_pchip' for 1 dates
Building PCHIP forwards for BTC-USD with provided timestamps
Constructing pillars for BTC-USD with swap and futures using provided timestamps
 - Time taken to fetch swap and futures: 0:00:00.000959
 - Time taken to align snapshots: 0:00:00.002481
 - Time taken to concatenate and filter: 0:00:00.642231
 - Time taken to index, drop and sort pillars: 0:00:00.000156
 - Total time taken to prepare pillars: 0:00:00.645827
 - Time taken to prepare pillars: 0:00:01.409647
 - Time taken to fit curves: 0:00:00.641702
 - Time taken to smooth curves: 0:00:00.711500
 - Time taken to convert to Polars: 0:00:00.175870
 - Total time taken to build PCHIP forwards: 0:00:02.938719
 - Time taken to fetch forwards: 0:00:03.081350
 - Time taken to build forward lookup: 0:00:00.198989

Matching forwards: 100%|██████████| 126245/126245 [00:13<00:00, 9055.42it/s]
LOEO pillar indices:  29%|██▊       | 2/7 [00:34<01:26, 17.25s/it]

 - Time taken to match forwards: 0:00:13.943488, matched 126,245 / 126,245 rows
 - Total time taken to assign forwards: 0:00:17.223827
Assigning pchip forwards to 1 dates using pchip forwards
 - Time taken to collect data: 0:00:00.000079
[store] Getting derived data via recipe 'build_forwards_pchip' for 1 dates
Building PCHIP forwards for BTC-USD with provided timestamps
Constructing pillars for BTC-USD with swap and futures using provided timestamps
 - Time taken to fetch swap and futures: 0:00:00.000900
 - Time taken to align snapshots: 0:00:00.002030
 - Time taken to concatenate and filter: 0:00:00.609142
 - Time taken to index, drop and sort pillars: 0:00:00.000174
 - Total time taken to prepare pillars: 0:00:00.612246
 - Time taken to prepare pillars: 0:00:01.373862
 - Time taken to fit curves: 0:00:00.658923
 - Time taken to smooth curves: 0:00:00.709739
 - Time taken to convert to Polars: 0:00:00.174633
 - Total time taken to build PCHIP forwards: 0:00:02.917157
 - Time taken to fetch forwards: 0:00:03.059992
 - Time taken to build forward lookup: 0:00:00.193595

Matching forwards: 100%|██████████| 126245/126245 [00:14<00:00, 9002.76it/s]
LOEO pillar indices:  43%|████▎     | 3/7 [00:51<01:09, 17.27s/it]

 - Time taken to match forwards: 0:00:14.025054, matched 126,245 / 126,245 rows
 - Total time taken to assign forwards: 0:00:17.278641
Assigning pchip forwards to 1 dates using pchip forwards
 - Time taken to collect data: 0:00:00.000112
[store] Getting derived data via recipe 'build_forwards_pchip' for 1 dates
Building PCHIP forwards for BTC-USD with provided timestamps
Constructing pillars for BTC-USD with swap and futures using provided timestamps
 - Time taken to fetch swap and futures: 0:00:00.000918
 - Time taken to align snapshots: 0:00:00.001964
 - Time taken to concatenate and filter: 0:00:00.653107
 - Time taken to index, drop and sort pillars: 0:00:00.000226
 - Total time taken to prepare pillars: 0:00:00.656215
 - Time taken to prepare pillars: 0:00:01.465038
 - Time taken to fit curves: 0:00:00.631035
 - Time taken to smooth curves: 0:00:00.807585
 - Time taken to convert to Polars: 0:00:00.167265
 - Total time taken to build PCHIP forwards: 0:00:03.070923
 - Time taken to fetch forwards: 0:00:03.218197
 - Time taken to build forward lookup: 0:00:00.205379

Matching forwards: 100%|██████████| 126245/126245 [00:14<00:00, 8847.74it/s]
LOEO pillar indices:  57%|█████▋    | 4/7 [01:09<00:52, 17.45s/it]

 - Time taken to match forwards: 0:00:14.270984, matched 126,245 / 126,245 rows
 - Total time taken to assign forwards: 0:00:17.694560
Assigning pchip forwards to 1 dates using pchip forwards
 - Time taken to collect data: 0:00:00.000451
[store] Getting derived data via recipe 'build_forwards_pchip' for 1 dates
Building PCHIP forwards for BTC-USD with provided timestamps
Constructing pillars for BTC-USD with swap and futures using provided timestamps
 - Time taken to fetch swap and futures: 0:00:00.004214
 - Time taken to align snapshots: 0:00:00.007505
 - Time taken to concatenate and filter: 0:00:00.630934
 - Time taken to index, drop and sort pillars: 0:00:00.000217
 - Total time taken to prepare pillars: 0:00:00.642870
 - Time taken to prepare pillars: 0:00:01.433953
 - Time taken to fit curves: 0:00:00.649847
 - Time taken to smooth curves: 0:00:00.716548
 - Time taken to convert to Polars: 0:00:00.174689
 - Total time taken to build PCHIP forwards: 0:00:02.975037
 - Time taken to fetch forwards: 0:00:03.123057
 - Time taken to build forward lookup: 0:00:00.194255

Matching forwards: 100%|██████████| 126245/126245 [00:14<00:00, 8726.53it/s]
LOEO pillar indices:  71%|███████▏  | 5/7 [01:27<00:35, 17.58s/it]

 - Time taken to match forwards: 0:00:14.468745, matched 126,245 / 126,245 rows
 - Total time taken to assign forwards: 0:00:17.786057
Assigning pchip forwards to 1 dates using pchip forwards
 - Time taken to collect data: 0:00:00.000102
[store] Getting derived data via recipe 'build_forwards_pchip' for 1 dates
Building PCHIP forwards for BTC-USD with provided timestamps
Constructing pillars for BTC-USD with swap and futures using provided timestamps
 - Time taken to fetch swap and futures: 0:00:00.001034
 - Time taken to align snapshots: 0:00:00.001915
 - Time taken to concatenate and filter: 0:00:00.622710
 - Time taken to index, drop and sort pillars: 0:00:00.000165
 - Total time taken to prepare pillars: 0:00:00.625824
 - Time taken to prepare pillars: 0:00:01.445400
 - Time taken to fit curves: 0:00:00.634252
 - Time taken to smooth curves: 0:00:00.709186
 - Time taken to convert to Polars: 0:00:00.283885
 - Total time taken to build PCHIP forwards: 0:00:03.072723
 - Time taken to fetch forwards: 0:00:03.223699
 - Time taken to build forward lookup: 0:00:00.119241

Matching forwards: 100%|██████████| 126245/126245 [00:14<00:00, 8963.90it/s]
LOEO pillar indices:  86%|████████▌ | 6/7 [01:44<00:17, 17.54s/it]

 - Time taken to match forwards: 0:00:14.085848, matched 126,245 / 126,245 rows
 - Total time taken to assign forwards: 0:00:17.428788
Assigning pchip forwards to 1 dates using pchip forwards
 - Time taken to collect data: 0:00:00.000101
[store] Getting derived data via recipe 'build_forwards_pchip' for 1 dates
Building PCHIP forwards for BTC-USD with provided timestamps
Constructing pillars for BTC-USD with swap and futures using provided timestamps
 - Time taken to fetch swap and futures: 0:00:00.000774
 - Time taken to align snapshots: 0:00:00.001988
 - Time taken to concatenate and filter: 0:00:00.614947
 - Time taken to index, drop and sort pillars: 0:00:00.000164
 - Total time taken to prepare pillars: 0:00:00.617873
 - Time taken to prepare pillars: 0:00:01.384449
 - Time taken to fit curves: 0:00:00.621962
 - Time taken to smooth curves: 0:00:00.791136
 - Time taken to convert to Polars: 0:00:00.165023
 - Total time taken to build PCHIP forwards: 0:00:02.962570
 - Time taken to fetch forwards: 0:00:03.106365
 - Time taken to build forward lookup: 0:00:00.198719

Matching forwards: 100%|██████████| 126245/126245 [00:14<00:00, 8964.66it/s]
LOEO pillar indices: 100%|██████████| 7/7 [02:02<00:00, 17.46s/it]

 - Time taken to match forwards: 0:00:14.084576, matched 126,245 / 126,245 rows
 - Total time taken to assign forwards: 0:00:17.389660

Summary:
shape: (1, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ error_mid_bps_ ┆ error_mid_bps_ ┆ error_bid_bps_ ┆ error_ask_bps ┆ spread_obs_bp ┆ spread_pred_b │
│ mean           ┆ std            ┆ mean           ┆ _mean         ┆ s_mean        ┆ ps_mean       │
│ ---            ┆ ---            ┆ ---            ┆ ---           ┆ ---           ┆ ---           │
│ f64            ┆ f64            ┆ f64            ┆ f64           ┆ f64           ┆ f64           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ 8.9736         ┆ 8.59131        ┆ 8.80849        ┆ 9.171643      ┆ 0.671846      ┆ 0.883548      │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

============================================================
Evaluating KALMAN on SINGLE DAY with OPTION TIMESTAMPS
============================================================


--- Put-Call Parity ---
Preparing paired options data for BTC-USD for 1 dates using build_forwards_kalman
[store] Getting BTC-USD/OPTION for 1 dates (depth=1, provided timestamps, 6 features)
 - Time taken to fetch options: 0:00:00.001097
[store] Getting BTC-USD/SPOT for 1 dates (depth=0, provided timestamps, 4 features)
 - Time taken to fetch spot: 0:00:00.000263
 - Time taken for numeraire conversion: 0:00:00.000038
Assigning kalman forwards to 1 dates using kalman forwards
 - Time taken to collect data: 0:00:00.564906
[store] Getting derived data via recipe 'build_forwards_kalman' for 1 dates
Building Kalman-filtered Nelson-Siegel forwards for BTC-USD with provided timestamps
Constructing pillars for BTC-USD with swap and futures using provided timestamps
 - Time taken to fetch swap and futures: 0:00:00.000647
 - Time taken to align snapshots: 0:00:00.006014
 - Time taken to concatenate and filter: 0:00:00.688333
 - Time taken to index and sort pillars: 0:00:00.000157
 - Total time taken to prepare pillars: 0:00:00.695151
 - Time taken to prepare and collect pillars: 0:00:01.694412
 - Time taken to build 399680 snapshots: 0:00:02.178464

Kalman filter:   0%|          | 0/399680 [00:00<?, ?it/s]

 - Time taken to run Kalman filter: 0:00:18.907856
 - Time taken to convert states to Polars: 0:00:00.064048
 - Total time taken to build Kalman forwards: 0:00:22.844780
 - Time taken to fetch forwards: 0:00:23.467176
 - Time taken to build forward lookup: 0:00:01.597454

Matching forwards: 100%|██████████| 399680/399680 [00:06<00:00, 61204.44it/s]

 - Time taken to match forwards: 0:00:06.539553, matched 749,637 / 749,637 rows
 - Total time taken to assign forwards: 0:00:31.604183
 - Time taken for forwards assignment and moneyness calculation: 0:00:31.626754
 - Total time taken for options data preparation: 0:00:31.628152

Summary:
shape: (1, 7)
┌─────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬─────────────┐
│ n_pairs ┆ error_mid_bp ┆ error_mid_bp ┆ error_bid_bp ┆ error_ask_bp ┆ call_spread_ ┆ put_spread_ │
│ ---     ┆ s_mean       ┆ s_std        ┆ s_mean       ┆ s_mean       ┆ bps_mean     ┆ bps_mean    │
│ u32     ┆ ---          ┆ ---          ┆ ---          ┆ ---          ┆ ---          ┆ ---         │
│         ┆ f64          ┆ f64          ┆ f64          ┆ f64          ┆ f64          ┆ f64         │
╞═════════╪══════════════╪══════════════╪══════════════╪══════════════╪══════════════╪═════════════╡
│ 683174  ┆ 6.0369       ┆ 180.631537   ┆ 5.959729     ┆ 6.114047     ┆ 462.103125   ┆ 475.229729  │
└─────────┴──────────────┴──────────────┴──────────────┴──────────────┴──────────────┴─────────────┘

--- Pillar Fit Quality ---
Preparing pillars for 1 dates...
Constructing pillars for BTC-USD with swap and futures using provided timestamps
 - Time taken to fetch swap and futures: 0:00:00.000841
 - Time taken to align snapshots: 0:00:00.090048
 - Time taken to concatenate and filter: 0:00:01.462085
 - Time taken to index and sort pillars: 0:00:00.000153
 - Total time taken to prepare pillars: 0:00:01.553127
Assigning kalman forwards to 1 dates using kalman forwards
 - Time taken to collect data: 0:00:05.732353
[store] Getting derived data via recipe 'build_forwards_kalman' for 1 dates
 - Time taken to fetch forwards: 0:00:05.859776
 - Time taken to build forward lookup: 0:00:01.416099

Matching forwards: 100%|██████████| 6312282/6312282 [00:08<00:00, 710079.62it/s]

 - Time taken to match forwards: 0:00:09.037143, matched 2,797,748 / 44,185,935 rows
 - Total time taken to assign forwards: 0:00:16.313018
Skipped 5,912,602 timestamp groups with no forward curve

Summary:
shape: (1, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ error_mid_bps_ ┆ error_mid_bps_ ┆ error_bid_bps_ ┆ error_ask_bps ┆ spread_obs_bp ┆ spread_pred_b │
│ mean           ┆ std            ┆ mean           ┆ _mean         ┆ s_mean        ┆ ps_mean       │
│ ---            ┆ ---            ┆ ---            ┆ ---           ┆ ---           ┆ ---           │
│ f64            ┆ f64            ┆ f64            ┆ f64           ┆ f64           ┆ f64           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ NaN            ┆ NaN            ┆ NaN            ┆ NaN           ┆ 0.672143      ┆ NaN           │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

--- Leave-One-Expiry-Out (sampled timestamps) ---
Using 126246 sampled timestamps
Running LOEO evaluation for 1 dates...
Constructing pillars for BTC-USD with swap and futures using provided timestamps
 - Time taken to fetch swap and futures: 0:00:00.002025
 - Time taken to align snapshots: 0:00:00.007954
 - Time taken to concatenate and filter: 0:00:00.674138
 - Time taken to index and sort pillars: 0:00:00.000178
 - Total time taken to prepare pillars: 0:00:00.684295
Evaluating 7 pillars...

LOEO pillar indices:   0%|          | 0/7 [00:00<?, ?it/s]

Assigning kalman forwards to 1 dates using kalman forwards
 - Time taken to collect data: 0:00:00.000118
[store] Getting derived data via recipe 'build_forwards_kalman' for 1 dates
Building Kalman-filtered Nelson-Siegel forwards for BTC-USD with provided timestamps
Constructing pillars for BTC-USD with swap and futures using provided timestamps
 - Time taken to fetch swap and futures: 0:00:00.001274
 - Time taken to align snapshots: 0:00:00.002149
 - Time taken to concatenate and filter: 0:00:00.661272
 - Time taken to index, drop and sort pillars: 0:00:00.000309
 - Total time taken to prepare pillars: 0:00:00.665004
 - Time taken to prepare and collect pillars: 0:00:01.463137
 - Time taken to build 126245 snapshots: 0:00:00.736317

Kalman filter:   0%|          | 0/126245 [00:00<?, ?it/s]

 - Time taken to run Kalman filter: 0:00:05.933549
 - Time taken to convert states to Polars: 0:00:00.020622
 - Total time taken to build Kalman forwards: 0:00:08.153625
 - Time taken to fetch forwards: 0:00:08.181293
 - Time taken to build forward lookup: 0:00:00.397423

Matching forwards: 100%|██████████| 126245/126245 [00:01<00:00, 69459.76it/s]
LOEO pillar indices:  14%|█▍        | 1/7 [00:10<01:02, 10.40s/it]

 - Time taken to match forwards: 0:00:01.819556, matched 126,245 / 126,245 rows
 - Total time taken to assign forwards: 0:00:10.398272
Assigning kalman forwards to 1 dates using kalman forwards
 - Time taken to collect data: 0:00:00.000086
[store] Getting derived data via recipe 'build_forwards_kalman' for 1 dates
Building Kalman-filtered Nelson-Siegel forwards for BTC-USD with provided timestamps
Constructing pillars for BTC-USD with swap and futures using provided timestamps
 - Time taken to fetch swap and futures: 0:00:00.000639
 - Time taken to align snapshots: 0:00:00.004153
 - Time taken to concatenate and filter: 0:00:00.631075
 - Time taken to index, drop and sort pillars: 0:00:00.000162
 - Total time taken to prepare pillars: 0:00:00.636029
 - Time taken to prepare and collect pillars: 0:00:01.398469
 - Time taken to build 126245 snapshots: 0:00:00.759880

Kalman filter:   0%|          | 0/126245 [00:00<?, ?it/s]

 - Time taken to run Kalman filter: 0:00:05.774027
 - Time taken to convert states to Polars: 0:00:00.019900
 - Total time taken to build Kalman forwards: 0:00:07.952276
 - Time taken to fetch forwards: 0:00:07.973733
 - Time taken to build forward lookup: 0:00:00.536566

Matching forwards: 100%|██████████| 126245/126245 [00:01<00:00, 70617.40it/s]
LOEO pillar indices:  29%|██▊       | 2/7 [00:20<00:51, 10.35s/it]

 - Time taken to match forwards: 0:00:01.789929, matched 126,245 / 126,245 rows
 - Total time taken to assign forwards: 0:00:10.300228
Assigning kalman forwards to 1 dates using kalman forwards
 - Time taken to collect data: 0:00:00.000305
[store] Getting derived data via recipe 'build_forwards_kalman' for 1 dates
Building Kalman-filtered Nelson-Siegel forwards for BTC-USD with provided timestamps
Constructing pillars for BTC-USD with swap and futures using provided timestamps
 - Time taken to fetch swap and futures: 0:00:00.002936
 - Time taken to align snapshots: 0:00:00.007828
 - Time taken to concatenate and filter: 0:00:00.613220
 - Time taken to index, drop and sort pillars: 0:00:00.000175
 - Total time taken to prepare pillars: 0:00:00.624159
 - Time taken to prepare and collect pillars: 0:00:01.379405
 - Time taken to build 126245 snapshots: 0:00:00.687370

Kalman filter:   0%|          | 0/126245 [00:00<?, ?it/s]

 - Time taken to run Kalman filter: 0:00:05.850633
 - Time taken to convert states to Polars: 0:00:00.021193
 - Total time taken to build Kalman forwards: 0:00:07.938601
 - Time taken to fetch forwards: 0:00:07.965483
 - Time taken to build forward lookup: 0:00:00.519814

Matching forwards: 100%|██████████| 126245/126245 [00:01<00:00, 70081.95it/s]
LOEO pillar indices:  43%|████▎     | 3/7 [00:31<00:41, 10.32s/it]

 - Time taken to match forwards: 0:00:01.803486, matched 126,245 / 126,245 rows
 - Total time taken to assign forwards: 0:00:10.288783
Assigning kalman forwards to 1 dates using kalman forwards
 - Time taken to collect data: 0:00:00.000071
[store] Getting derived data via recipe 'build_forwards_kalman' for 1 dates
Building Kalman-filtered Nelson-Siegel forwards for BTC-USD with provided timestamps
Constructing pillars for BTC-USD with swap and futures using provided timestamps
 - Time taken to fetch swap and futures: 0:00:00.001875
 - Time taken to align snapshots: 0:00:00.005607
 - Time taken to concatenate and filter: 0:00:00.614558
 - Time taken to index, drop and sort pillars: 0:00:00.000159
 - Total time taken to prepare pillars: 0:00:00.622199
 - Time taken to prepare and collect pillars: 0:00:01.371866
 - Time taken to build 126245 snapshots: 0:00:00.691648

Kalman filter:   0%|          | 0/126245 [00:00<?, ?it/s]

 - Time taken to run Kalman filter: 0:00:05.886761
 - Time taken to convert states to Polars: 0:00:00.020822
 - Total time taken to build Kalman forwards: 0:00:07.971097
 - Time taken to fetch forwards: 0:00:07.994076
 - Time taken to build forward lookup: 0:00:00.536945

Matching forwards: 100%|██████████| 126245/126245 [00:01<00:00, 67074.92it/s]
LOEO pillar indices:  57%|█████▋    | 4/7 [00:41<00:31, 10.36s/it]

 - Time taken to match forwards: 0:00:01.884761, matched 126,245 / 126,245 rows
 - Total time taken to assign forwards: 0:00:10.415782
Assigning kalman forwards to 1 dates using kalman forwards
 - Time taken to collect data: 0:00:00.000082
[store] Getting derived data via recipe 'build_forwards_kalman' for 1 dates
Building Kalman-filtered Nelson-Siegel forwards for BTC-USD with provided timestamps
Constructing pillars for BTC-USD with swap and futures using provided timestamps
 - Time taken to fetch swap and futures: 0:00:00.001438
 - Time taken to align snapshots: 0:00:00.001999
 - Time taken to concatenate and filter: 0:00:00.626002
 - Time taken to index, drop and sort pillars: 0:00:00.000158
 - Total time taken to prepare pillars: 0:00:00.629597
 - Time taken to prepare and collect pillars: 0:00:01.428339
 - Time taken to build 126245 snapshots: 0:00:00.639806

Kalman filter:   0%|          | 0/126245 [00:00<?, ?it/s]

 - Time taken to run Kalman filter: 0:00:06.034478
 - Time taken to convert states to Polars: 0:00:00.021095
 - Total time taken to build Kalman forwards: 0:00:08.123718
 - Time taken to fetch forwards: 0:00:08.147126
 - Time taken to build forward lookup: 0:00:00.399915

Matching forwards: 100%|██████████| 126245/126245 [00:01<00:00, 67749.89it/s]
LOEO pillar indices:  71%|███████▏  | 5/7 [00:51<00:20, 10.38s/it]

 - Time taken to match forwards: 0:00:01.865246, matched 126,245 / 126,245 rows
 - Total time taken to assign forwards: 0:00:10.412287
Assigning kalman forwards to 1 dates using kalman forwards
 - Time taken to collect data: 0:00:00.000087
[store] Getting derived data via recipe 'build_forwards_kalman' for 1 dates
Building Kalman-filtered Nelson-Siegel forwards for BTC-USD with provided timestamps
Constructing pillars for BTC-USD with swap and futures using provided timestamps
 - Time taken to fetch swap and futures: 0:00:00.000783
 - Time taken to align snapshots: 0:00:00.001975
 - Time taken to concatenate and filter: 0:00:00.607961
 - Time taken to index, drop and sort pillars: 0:00:00.000217
 - Total time taken to prepare pillars: 0:00:00.610936
 - Time taken to prepare and collect pillars: 0:00:01.374688
 - Time taken to build 126245 snapshots: 0:00:00.753017

Kalman filter:   0%|          | 0/126245 [00:00<?, ?it/s]

 - Time taken to run Kalman filter: 0:00:05.923909
 - Time taken to convert states to Polars: 0:00:00.020203
 - Total time taken to build Kalman forwards: 0:00:08.071817
 - Time taken to fetch forwards: 0:00:08.094643
 - Time taken to build forward lookup: 0:00:00.396831

Matching forwards: 100%|██████████| 126245/126245 [00:01<00:00, 68858.93it/s]
LOEO pillar indices:  86%|████████▌ | 6/7 [01:02<00:10, 10.37s/it]

 - Time taken to match forwards: 0:00:01.836005, matched 126,245 / 126,245 rows
 - Total time taken to assign forwards: 0:00:10.327479
Assigning kalman forwards to 1 dates using kalman forwards
 - Time taken to collect data: 0:00:00.000211
[store] Getting derived data via recipe 'build_forwards_kalman' for 1 dates
Building Kalman-filtered Nelson-Siegel forwards for BTC-USD with provided timestamps
Constructing pillars for BTC-USD with swap and futures using provided timestamps
 - Time taken to fetch swap and futures: 0:00:00.000808
 - Time taken to align snapshots: 0:00:00.004082
 - Time taken to concatenate and filter: 0:00:00.674507
 - Time taken to index, drop and sort pillars: 0:00:00.000160
 - Total time taken to prepare pillars: 0:00:00.679557
 - Time taken to prepare and collect pillars: 0:00:01.454682
 - Time taken to build 126245 snapshots: 0:00:00.776425

Kalman filter:   0%|          | 0/126245 [00:00<?, ?it/s]

 - Time taken to run Kalman filter: 0:00:05.929108
 - Time taken to convert states to Polars: 0:00:00.020579
 - Total time taken to build Kalman forwards: 0:00:08.180794
 - Time taken to fetch forwards: 0:00:08.205733
 - Time taken to build forward lookup: 0:00:00.401015

Matching forwards: 100%|██████████| 126245/126245 [00:01<00:00, 68968.29it/s]
LOEO pillar indices: 100%|██████████| 7/7 [01:12<00:00, 10.38s/it]

 - Time taken to match forwards: 0:00:01.832433, matched 126,245 / 126,245 rows
 - Total time taken to assign forwards: 0:00:10.439181

Summary:
shape: (1, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ error_mid_bps_ ┆ error_mid_bps_ ┆ error_bid_bps_ ┆ error_ask_bps ┆ spread_obs_bp ┆ spread_pred_b │
│ mean           ┆ std            ┆ mean           ┆ _mean         ┆ s_mean        ┆ ps_mean       │
│ ---            ┆ ---            ┆ ---            ┆ ---           ┆ ---           ┆ ---           │
│ f64            ┆ f64            ┆ f64            ┆ f64           ┆ f64           ┆ f64           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ 4.542814       ┆ 4.866417       ┆ 4.714588       ┆ 4.428058      ┆ 0.671846      ┆ 0.009732      │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

## Comparison Across Scenarios

Compare PCHIP vs Kalman performance across both scenarios.

In [ ]:
print("\n" + "="*60)
print("COMPARISON SUMMARY")
print("="*60)

# Put-call parity comparison
print("\n--- Put-Call Parity Errors (bps) ---\n")
comparison_data = []
for scenario, results in [('Month+Binning', results_month), ('Day+Options', results_day)]:
    for recipe_name in recipes.keys():
        df_parity = results[recipe_name]['parity']
        if not df_parity.is_empty():
            comparison_data.append({
                'scenario': scenario,
                'recipe': recipe_name,
                'n_pairs': len(df_parity),
                'error_mid_mean': df_parity['error_mid_bps'].mean(),
                'error_mid_std': df_parity['error_mid_bps'].std(),
            })

if comparison_data:
    print(pl.DataFrame(comparison_data))

# Pillar fit comparison
print("\n--- Pillar Fit WMAE (bps) ---\n")
comparison_data = []
for scenario, results in [('Month+Binning', results_month), ('Day+Options', results_day)]:
    for recipe_name in recipes.keys():
        df_fit = results[recipe_name]['pillar_fit']
        if not df_fit.is_empty():
            for side in ['bid', 'ask', 'mid']:
                side_data = df_fit.filter(pl.col('side') == side)
                if not side_data.is_empty():
                    comparison_data.append({
                        'scenario': scenario,
                        'recipe': recipe_name,
                        'side': side,
                        'mean_wmae': side_data['wmae_bps'].mean(),
                        'max_error': side_data['max_error_bps'].max(),
                    })

if comparison_data:
    print(pl.DataFrame(comparison_data))

# LOEO comparison
print("\n--- LOEO Errors (bps) ---\n")
comparison_data = []
for scenario, results in [('Month+Binning', results_month), ('Day+Options', results_day)]:
    for recipe_name in recipes.keys():
        df_loeo = results[recipe_name]['loeo']
        if not df_loeo.is_empty():
            success_df = df_loeo.filter(pl.col('success'))
            if not success_df.is_empty():
                comparison_data.append({
                    'scenario': scenario,
                    'recipe': recipe_name,
                    'n_tests': len(success_df),
                    'mean_error_mid': success_df['error_mid_bps'].mean(),
                    'max_error_mid': success_df['error_mid_bps'].max(),
                })

if comparison_data:
    print(pl.DataFrame(comparison_data))

---

## Key Takeaways

This evaluation framework provides a comprehensive assessment of forward curve quality:

1. **Put-call parity** validates consistency with options market
2. **Pillar fit** measures how well the curve fits observed forward prices
3. **LOEO** tests out-of-sample prediction performance

The modular design allows easy comparison across:
- Different recipes (PCHIP vs Kalman)
- Different time horizons (full month vs single day)
- Different sampling strategies (binning vs option timestamps)